"""add unique constraint for name x user_id in tenants table

Revision ID: 455b6b97f693
Revises: e015f3a1a0d5
Create Date: 2026-04-05 18:05:38.476635

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "455b6b97f693"
down_revision: Union[str, Sequence[str], None] = "e015f3a1a0d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_tenants_name_user_id", "tenants", ["name", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tenants_name_user_id", "tenants", type_="unique")
    # ### end Alembic commands ###
