"""add tenant_policy_id to audit_events table

Revision ID: dc44c3282a63
Revises: 2ef14ed68f7a
Create Date: 2026-04-11 20:29:58.902209

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc44c3282a63"
down_revision: Union[str, Sequence[str], None] = "2ef14ed68f7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events", sa.Column("tenant_policy_id", sa.UUID(), nullable=False)
    )
    op.create_foreign_key(
        "audit_events_tenant_policy_id_fkey",
        "audit_events",
        "tenant_policies",
        ["tenant_policy_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "audit_events_tenant_policy_id_fkey", "audit_events", type_="foreignkey"
    )
    op.drop_column("audit_events", "tenant_policy_id")
    # ### end Alembic commands ###
